#!/bin/bash

module purge
module load envvar/1.0
module load prod_util/2.0.10
set -x

# mirror  RRFSUPP files from prod to dev
#PDY=20230308
#cyc=02

CURRENTDATE=$PDY$CYC

mysite=$(cat /etc/cluster_name)
primary=$(head -1 /lfs/h1/ops/prod/config/prodmachinefile | cut -d ":" -f2-)
backup=$(head -2 /lfs/h1/ops/prod/config/prodmachinefile | tail -1 | cut -d ":" -f2-)

if [ "$primary" == "cactus" ]; then
  desmachine=emc.lam@ddxfer.wcoss2.ncep.noaa.gov
else
  desmachine=emc.lam@cdxfer.wcoss2.ncep.noaa.gov
fi

#sourcemachine=emc.lam@ddxfer.wcoss2.ncep.noaa.gov
#desmachine=emc.lam@cdxfer.wcoss2.ncep.noaa.gov

#for hourback  in 1 2 3 4 5 6

indx="03 04 05 06 07 08 15 16 17 18 19 20"

for hourback  in 1 2 3 4 5 6
do
  #YYYYMMDDHH=`date +"%Y%m%d%H" -d "${CURRENTDATE} ${minsback} minute ago"`
  #currentdate=`date +"%Y%m%d %H"`
  YYYYMMDDHH=`$NDATE -$hourback $CURRENTDATE`

  PDY=`echo ${YYYYMMDDHH} | cut -c1-8`
  cyc=`echo ${YYYYMMDDHH} | cut -c9-10`

  proddir=/lfs/h2/emc/ptmp/emc.lam/rrfs/conus/prod/rrfs_a.${PDY}/${cyc}
  proddir_spinup=/lfs/h2/emc/ptmp/emc.lam/rrfs/conus/prod/rrfs_a.${PDY}/${cyc}_spinup
  proddir1=/lfs/h2/emc/ptmp/emc.lam/rrfs/conus/prod/rrfs_a.${PDY}
  destination=/lfs/h2/emc/ptmp/emc.lam/rrfs/v0.3.8_${primary}/prod/rrfs_a.${PDY}
  destination1=/lfs/h2/emc/ptmp/emc.lam/rrfs/v0.3.8_${primary}/prod
  touch $proddir1/dummy
  rsync -aq $proddir1/dummy $desmachine:$destination/
  rsync -arv $proddir $desmachine:$destination

  for i in $indx
  do
   if [ "$cyc" == $i ]; then
     proddir_spinup=/lfs/h2/emc/ptmp/emc.lam/rrfs/conus/prod/rrfs_a.${PDY}/${cyc}_spinup
     rsync -arv $proddir_spinup $desmachine:$destination
   fi
  done

done

exit
