#!/bin/bash

module purge
module load envvar/1.0
module load prod_util/2.0.10
set -x

# mirror  RRFSUPP files from prod to dev
#PDY=20230308
#cyc=02
version=$RRFSVER

CURRENTDATE=$PDY$CYC

mysite=$(cat /etc/cluster_name)
primary=$(head -1 /lfs/h1/ops/prod/config/prodmachinefile | cut -d ":" -f2-)
backup=$(head -2 /lfs/h1/ops/prod/config/prodmachinefile | tail -1 | cut -d ":" -f2-)

if [ "$primary" == "cactus" ]; then
  desmachine=emc.lam@ddxfer.wcoss2.ncep.noaa.gov
else
  desmachine=emc.lam@cdxfer.wcoss2.ncep.noaa.gov
fi

#sourcemachine=emc.lam@ddxfer.wcoss2.ncep.noaa.gov
#desmachine=emc.lam@cdxfer.wcoss2.ncep.noaa.gov

indx="00 06 12 18"

#for hourback  in 1 2 3 4 5 6
for hourback  in 0 1 2 3 4 5 6
do
  #YYYYMMDDHH=`date +"%Y%m%d%H" -d "${CURRENTDATE} ${minsback} minute ago"`
  #currentdate=`date +"%Y%m%d %H"`
  YYYYMMDDHH=`$NDATE -$hourback $CURRENTDATE`

  PDY=`echo ${YYYYMMDDHH} | cut -c1-8`
  cyc=`echo ${YYYYMMDDHH} | cut -c9-10`

  proddir_nwges=/lfs/h2/emc/ptmp/emc.lam/rrfs/conus/nwges
  destination_nwges=/lfs/h2/emc/ptmp/emc.lam/rrfs/${version}/nwges
  touch $proddir_nwges/dummy
  rsync -aq $proddir_nwges/dummy $desmachine:$destination_nwges/

  proddir_day=/lfs/h2/emc/ptmp/emc.lam/rrfs/conus/nwges/${PDY}${cyc}
  destination_day=/lfs/h2/emc/ptmp/emc.lam/rrfs/${version}/nwges/${PDY}${cyc}
  touch $proddir_day/dummy
  rsync -aq $proddir_day/dummy $desmachine:$destination_day/
  rsync -arv $proddir_day/fcst_fv3lam $desmachine:$destination_day

  rsync -arv $proddir_nwges/enkf_diag $desmachine:$destination_nwges
  rsync -arv $proddir_nwges/observer_diag $desmachine:$destination_nwges
  rsync -arv $proddir_nwges/satbias $desmachine:$destination_nwges
  rsync -arv $proddir_nwges/satbias_ensmean $desmachine:$destination_nwges
  rsync -arv $proddir_nwges/RAVE_INTP $desmachine:$destination_nwges
  rsync -arv $proddir_nwges/surface $desmachine:$destination_nwges

  for i in $indx
  do
   if [ "$cyc" == $i ]; then
     rsync -arv $proddir_day/lbcs $desmachine:$destination_day
   fi
  done
done

exit
