#!/bin/bash

module purge
module load envvar/1.0
module load prod_util/2.0.10
. ${GLOBAL_VAR_DEFNS_FP}

set -x

# mirror  RRFSUPP files from prod to dev
#PDY=20230308
#cyc=02

CURRENTDATE=$PDY$CYC

mysite=$(cat /etc/cluster_name)
primary=$(head -1 /lfs/h1/ops/prod/config/prodmachinefile | cut -d ":" -f2-)
backup=$(head -2 /lfs/h1/ops/prod/config/prodmachinefile | tail -1 | cut -d ":" -f2-)

if [ "$primary" == "cactus" ]; then
  desmachine=emc.lam@ddxfer.wcoss2.ncep.noaa.gov
else
  desmachine=emc.lam@cdxfer.wcoss2.ncep.noaa.gov
fi

#for hourback  in 1 2 3 4 5 6

indx="00 06 12 18"

for hourback in 0 1 2 3 4 5 6 7 8 9 10 11 12
do
  #YYYYMMDDHH=`date +"%Y%m%d%H" -d "${CURRENTDATE} ${minsback} minute ago"`
  #currentdate=`date +"%Y%m%d %H"`
  YYYYMMDDHH=`$NDATE -$hourback $CURRENTDATE`

  PDY=`echo ${YYYYMMDDHH} | cut -c1-8`
  cyc=`echo ${YYYYMMDDHH} | cut -c9-10`

  for i in $indx
  do
   if [ "$cyc" == $i ]; then

     proddir_day=/lfs/h2/emc/ptmp/emc.lam/rrfs/conus/prod_enfcst/rrfs_a.${PDY}
     destination_day=/lfs/h2/emc/ptmp/emc.lam/rrfs/v0.3.8_${primary}/prod_enfcst
     touch $proddir_day/dummy
     rsync -aq $proddir_day/dummy $desmachine:$destination_day/

     proddir_day_cyc=/lfs/h2/emc/ptmp/emc.lam/rrfs/conus/prod_enfcst/rrfs_a.${PDY}/${cyc}
     destination_day_cyc=/lfs/h2/emc/ptmp/emc.lam/rrfs/v0.3.8_${primary}/prod_enfcst/rrfs_a.${PDY}
     touch $proddir_day_cyc/dummy
     rsync -aq $proddir_day_cyc/dummy $desmachine:$destination_day_cyc/

     rsync -arv $proddir/mem0001 $desmachine:$destination
     rsync -arv $proddir/mem0002 $desmachine:$destination
     rsync -arv $proddir/mem0003 $desmachine:$destination
     rsync -arv $proddir/mem0004 $desmachine:$destination
     rsync -arv $proddir/mem0005 $desmachine:$destination
   fi
  done

# for i in $indx
# do
#  if [ "$cyc" == $i ]; then
#    proddir_spinup=/lfs/h2/emc/ptmp/emc.lam/rrfs/conus/prod/rrfs_a.${PDY}/${cyc}_spinup
#    rsync -arv $proddir_spinup $desmachine:$destination
#  fi
# done

done

exit
